{"uuid": "2513ee14-2e68-498e-8acd-800a653b1307", "children": ["808ddbb5-e124-45fa-80a7-fb192c8abf7f"], "befores": [{"name": "xunit_setup_method_fixture_TestIosSample", "status": "passed", "start": 1612332404095, "stop": 1612332407541}], "afters": [{"name": "xunit_setup_method_fixture_TestIosSample::0", "status": "broken", "statusDetails": {"message": "RuntimeError: call depth exceed 4\n", "trace": "  File \"/Users/yangkang/Desktop/myproject/ytest/venv/lib/python3.8/site-packages/allure_commons/_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/Users/yangkang/Desktop/myproject/ytest/venv/lib/python3.8/site-packages/_pytest/fixtures.py\", line 941, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/yangkang/Desktop/myproject/ytest/venv/lib/python3.8/site-packages/_pytest/python.py\", line 845, in xunit_setup_method_fixture\n    _call_with_optional_argument(func, method)\n  File \"/Users/yangkang/Desktop/myproject/ytest/venv/lib/python3.8/site-packages/_pytest/python.py\", line 739, in _call_with_optional_argument\n    func(arg)\n  File \"/Users/yangkang/Desktop/myproject/ytest/case/ios/__init__.py\", line 18, in teardown_method\n    self.s.app_terminate(self.app_name)\n  File \"/Users/yangkang/Desktop/myproject/ytest/venv/lib/python3.8/site-packages/wda/__init__.py\", line 821, in app_terminate\n    return self._session_http.post(\"/wda/apps/terminate\", {\n  File \"/Users/yangkang/Desktop/myproject/ytest/venv/lib/python3.8/site-packages/wda/utils.py\", line 47, in _inner\n    return fn(*args, **kwargs)\n  File \"/Users/yangkang/Desktop/myproject/ytest/venv/lib/python3.8/site-packages/wda/__init__.py\", line 460, in _fetch\n    return self._fetch(method, urlpath, data, with_session)\n  File \"/Users/yangkang/Desktop/myproject/ytest/venv/lib/python3.8/site-packages/wda/utils.py\", line 47, in _inner\n    return fn(*args, **kwargs)\n  File \"/Users/yangkang/Desktop/myproject/ytest/venv/lib/python3.8/site-packages/wda/__init__.py\", line 460, in _fetch\n    return self._fetch(method, urlpath, data, with_session)\n  File \"/Users/yangkang/Desktop/myproject/ytest/venv/lib/python3.8/site-packages/wda/utils.py\", line 47, in _inner\n    return fn(*args, **kwargs)\n  File \"/Users/yangkang/Desktop/myproject/ytest/venv/lib/python3.8/site-packages/wda/__init__.py\", line 460, in _fetch\n    return self._fetch(method, urlpath, data, with_session)\n  File \"/Users/yangkang/Desktop/myproject/ytest/venv/lib/python3.8/site-packages/wda/utils.py\", line 47, in _inner\n    return fn(*args, **kwargs)\n  File \"/Users/yangkang/Desktop/myproject/ytest/venv/lib/python3.8/site-packages/wda/__init__.py\", line 460, in _fetch\n    return self._fetch(method, urlpath, data, with_session)\n  File \"/Users/yangkang/Desktop/myproject/ytest/venv/lib/python3.8/site-packages/wda/utils.py\", line 47, in _inner\n    return fn(*args, **kwargs)\n  File \"/Users/yangkang/Desktop/myproject/ytest/venv/lib/python3.8/site-packages/wda/__init__.py\", line 460, in _fetch\n    return self._fetch(method, urlpath, data, with_session)\n  File \"/Users/yangkang/Desktop/myproject/ytest/venv/lib/python3.8/site-packages/wda/utils.py\", line 43, in _inner\n    raise RuntimeError(\"call depth exceed %d\" % n)\n"}, "start": 1612332421375, "stop": 1612332421434}], "start": 1612332404094, "stop": 1612332421434}